export default [
    {
      extension: 'null',
      sub_type: 0,
      name: '应出勤天数',
      alias: 'should_attendance_days',
      expression_id: 950457689,
      id: 950464689,
      type: 0,
      status: 0,
      visible: true
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '补卡次数',
      alias: 'making_up_lack_times',
      expression_id: 950457690,
      type: 0,
      status: 0
    },
    {
      extension: 'null',
      sub_type: 2,
      name: '出勤班次',
      alias: 'attendance_class',
      expression_id: 950457691,
      id: 950464691,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '出勤天数',
      alias: 'attendance_days',
      expression_id: 950457692,
      id: 950464692,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '休息天数',
      alias: 'attendance_rest_days',
      expression_id: 950457693,
      id: 950464693,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '工作时长',
      alias: 'attendance_work_time',
      expression_id: 950457694,
      id: 950464694,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '迟到次数',
      alias: 'late_times',
      expression_id: 950457695,
      id: 950464695,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '迟到时长',
      alias: 'late_minute',
      expression_id: 950457696,
      id: 950464696,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '严重迟到次数',
      alias: 'serious_late_times',
      expression_id: 950457697,
      id: 950464697,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '严重迟到时长',
      alias: 'serious_late_minute',
      expression_id: 950457698,
      id: 950464698,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '旷工迟到次数',
      alias: 'absenteeism_late_times',
      expression_id: 950457699,
      id: 950464699,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '早退次数',
      alias: 'leave_early_times',
      expression_id: 950457700,
      id: 950464700,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '早退时长',
      alias: 'leave_early_minute',
      expression_id: 950457701,
      id: 950464701,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '上班缺卡次数',
      alias: 'on_work_lack_card_times',
      expression_id: 950457702,
      id: 950464702,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '下班缺卡次数',
      alias: 'off_work_lack_card_times',
      expression_id: 950457703,
      id: 950464703,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '旷工天数',
      alias: 'absenteeism_days',
      expression_id: 950457704,
      id: 950464704,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '出差时长',
      alias: 'business_trip_time',
      expression_id: 950457705,
      id: 950464705,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '外出时长',
      alias: 'out_time',
      expression_id: 950457706,
      id: 950464706,
      type: 0,
      status: 0,
    },
    {
      sub_type: 0,
      name: '事假',
      alias: 'leave_',
      type: 0,
      status: 0,
    },
    {
      sub_type: 0,
      name: '调休',
      alias: 'leave_',
      type: 0,
      status: 0,
    },
    {
      sub_type: 0,
      name: '病假',
      alias: 'leave_',
      type: 0,
      status: 0,
    },
    {
      sub_type: 0,
      name: '年假',
      alias: 'leave_',
      type: 0,
      status: 0,
    },
    {
      sub_type: 0,
      name: '产假',
      alias: 'leave_',
      type: 0,
      status: 0,
    },
    {
      sub_type: 0,
      name: '陪产假',
      alias: 'leave_',
      type: 0,
      status: 0,
    },
    {
      sub_type: 0,
      name: '婚假',
      alias: 'leave_',
      type: 0,
      status: 0,
    },
    {
      sub_type: 0,
      name: '例假',
      alias: 'leave_',
      type: 0,
      status: 0,
    },
    {
      sub_type: 0,
      name: '丧假',
      alias: 'leave_',
      type: 0,
      status: 0,
    },
    {
      sub_type: 0,
      name: '哺乳假',
      alias: 'leave_',
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '加班-审批单统计',
      alias: 'overtime_approve_count',
      expression_id: 950457708,
      id: 950464708,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '工作日加班',
      alias: 'overtime_工作日加班',
      expression_id: 950457709,
      id: 950464709,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '休息日加班',
      alias: 'overtime_休息日加班',
      expression_id: 950457710,
      id: 950464710,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '节假日加班',
      alias: 'overtime_节假日加班',
      expression_id: 950457711,
      id: 950464711,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 1,
      name: '考勤结果',
      alias: 'attend_result',
      expression_id: 950457712,
      id: 950464712,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '班次',
      alias: 'plan_detail',
      expression_id: 950457713,
      id: 950464713,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '上班1打卡时间',
      alias: '1_on_duty_user_check_time',
      expression_id: 950457714,
      id: 950464714,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '上班1打卡结果',
      alias: '1_on_duty_user_check_result',
      expression_id: 950457715,
      id: 950464715,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '下班1打卡时间',
      alias: '1_off_duty_user_check_time',
      expression_id: 950457716,
      id: 950464716,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '下班1打卡结果',
      alias: '1_off_duty_user_check_result',
      expression_id: 950457717,
      id: 950464717,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '上班2打卡时间',
      alias: '2_on_duty_user_check_time',
      expression_id: 950457718,
      id: 950464718,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '上班2打卡结果',
      alias: '2_on_duty_user_check_result',
      expression_id: 950457719,
      id: 950464719,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '下班2打卡时间',
      alias: '2_off_duty_user_check_time',
      expression_id: 950457720,
      id: 950464720,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '下班2打卡结果',
      alias: '2_off_duty_user_check_result',
      expression_id: 950457721,
      id: 950464721,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '上班3打卡时间',
      alias: '3_on_duty_user_check_time',
      expression_id: 950457722,
      id: 950464722,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '上班3打卡结果',
      alias: '3_on_duty_user_check_result',
      expression_id: 950457723,
      id: 950464723,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '下班3打卡时间',
      alias: '3_off_duty_user_check_time',
      expression_id: 950457724,
      id: 950464724,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '下班3打卡结果',
      alias: '3_off_duty_user_check_result',
      expression_id: 950457725,
      id: 950464725,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '关联的审批单',
      alias: 'attendance_approve',
      expression_id: 950457726,
      id: 950464726,
      type: 0,
      status: 0,
    },
    {
      extension: 'null',
      sub_type: 0,
      name: '旷工迟到天数',
      alias: 'absenteeism_late_times',
      expression_id: 950457727,
      id: 950464727,
      type: 0,
      status: 0,
    },
  ];
