export default {
  name: 'basic_cg_detail',
  title: '采购明细基础表',
  inherit: false,
  hidden: false,
  description: null,
  fields: [
    {
      name: 'id',
      type: 'bigInt',
      interface: 'id',
      description: null,

      parentKey: null,
      reverseKey: null,
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      uiSchema: {
        type: 'number',
        title: '{{t("ID")}}',
        'x-component': 'InputNumber',
        'x-read-pretty': true,
      },
    },
    {
      name: 'cgUnit_id',
      type: 'bigInt',
      interface: 'integer',
      description: null,

      parentKey: null,
      reverseKey: null,
      isForeignKey: true,
      uiSchema: {
        type: 'number',
        title: 'cgUnit_id',
        'x-component': 'InputNumber',
        'x-read-pretty': true,
      },
    },
    {
      name: 'createdAt',
      type: 'date',
      interface: 'createdAt',
      description: null,

      parentKey: null,
      reverseKey: null,
      field: 'createdAt',
      uiSchema: {
        type: 'datetime',
        title: '{{t("Created at")}}',
        'x-component': 'DatePicker',
        'x-component-props': {},
        'x-read-pretty': true,
      },
    },
    {
      name: 'createdBy',
      type: 'belongsTo',
      interface: 'createdBy',
      description: null,

      parentKey: null,
      reverseKey: null,
      target: 'users',
      foreignKey: 'createdById',
      uiSchema: {
        type: 'object',
        title: '{{t("Created by")}}',
        'x-component': 'AssociationField',
        'x-component-props': {
          fieldNames: {
            value: 'id',
            label: 'nickname',
          },
        },
        'x-read-pretty': true,
      },
      targetKey: 'id',
    },
    {
      name: 'updatedAt',
      type: 'date',
      interface: 'updatedAt',
      description: null,

      parentKey: null,
      reverseKey: null,
      field: 'updatedAt',
      uiSchema: {
        type: 'string',
        title: '{{t("Last updated at")}}',
        'x-component': 'DatePicker',
        'x-component-props': {},
        'x-read-pretty': true,
      },
    },
    {
      name: 'updatedBy',
      type: 'belongsTo',
      interface: 'updatedBy',
      description: null,

      parentKey: null,
      reverseKey: null,
      target: 'users',
      foreignKey: 'updatedById',
      uiSchema: {
        type: 'object',
        title: '{{t("Last updated by")}}',
        'x-component': 'AssociationField',
        'x-component-props': {
          fieldNames: {
            value: 'id',
            label: 'nickname',
          },
        },
        'x-read-pretty': true,
      },
      targetKey: 'id',
    },
    {
      name: 'cgNum',
      type: 'bigInt',
      interface: 'integer',
      description: null,

      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'number',
        'x-component': 'InputNumber',
        'x-component-props': {
          stringMode: true,
          step: '1',
        },
        'x-validator': 'integer',
        title: '采购数量',
      },
    },
    {
      name: 'cgUnit',
      type: 'belongsTo',
      interface: 'obo',
      description: null,

      parentKey: null,
      reverseKey: null,
      foreignKey: 'cgUnit_id',
      onDelete: 'SET NULL',
      uiSchema: {
        'x-component': 'AssociationField',
        'x-component-props': {
          multiple: false,
          fieldNames: {
            label: 'id',
            value: 'id',
          },
        },
        title: '采购单位',
      },
      target: 'base_units',
      targetKey: 'id',
    },
    {
      name: 'rate',
      type: 'float',
      interface: 'percent',
      description: null,

      parentKey: null,
      reverseKey: null,
      uiSchema: {
        'x-component-props': {
          step: '1',
          stringMode: true,
          addonAfter: '%',
        },
        type: 'string',
        'x-component': 'Percent',
        title: ' 增值税税率(%)',
      },
      defaultValue: 0.13,
    },
    {
      name: 'price',
      type: 'double',
      interface: 'number',
      description: null,

      parentKey: null,
      reverseKey: null,
      uiSchema: {
        'x-component-props': {
          step: '0.00001',
          stringMode: true,
        },
        type: 'number',
        'x-component': 'InputNumber',
        title: '含税单价',
      },
    },
    {
      name: 'base_price',
      type: 'formula',
      interface: 'formula',
      description: null,

      parentKey: null,
      reverseKey: null,
      dataType: 'double',
      uiSchema: {
        'x-component-props': {
          step: '0.00001',
          stringMode: true,
        },
        type: 'string',
        'x-component': 'Formula.Result',
        'x-read-pretty': true,
        title: '参考单价',
      },
      engine: 'formula.js',
      expression: '{{price}}/(1+{{rate}})',
    },
    {
      name: 'total_price',
      type: 'formula',
      interface: 'formula',
      description: null,

      parentKey: null,
      reverseKey: null,
      dataType: 'double',
      uiSchema: {
        'x-component-props': {
          step: '1',
          stringMode: true,
        },
        type: 'string',
        'x-component': 'Formula.Result',
        'x-read-pretty': true,
        title: '金额',
      },
      engine: 'formula.js',
      expression: '{{price}}*{{cgNum}}',
    },
    {
      name: 'taxi',
      type: 'formula',
      interface: 'formula',
      description: null,

      parentKey: null,
      reverseKey: null,
      dataType: 'double',
      uiSchema: {
        'x-component-props': {
          step: '0.00001',
          stringMode: true,
        },
        type: 'string',
        'x-component': 'Formula.Result',
        'x-read-pretty': true,
        title: '税额',
      },
      engine: 'formula.js',
      expression: '{{cgNum}}*({{price}}*{{rate}}/(1+{{rate}}))',
    },
    {
      name: 'link',
      type: 'text',
      interface: 'textarea',
      description: null,

      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'string',
        'x-component': 'Input.TextArea',
        title: '平台链接',
      },
    },
  ],
  logging: true,
  autoGenId: true,
  createdBy: true,
  updatedBy: true,
  createdAt: true,
  updatedAt: true,
  sortable: true,
  template: 'general',
  view: false,
  schema: 'public',
};
