export default {
  name: 'wl_info',
  title: '物料信息',
  inherit: false,
  hidden: false,
  category: [
    {
      id: 3,
      createdAt: '2023-11-09T05:19:17.015Z',
      updatedAt: '2023-11-10T09:04:34.555Z',
      name: '物料',
      color: 'default',
      collectionCategory: {
        createdAt: '2023-11-09T05:54:48.931Z',
        updatedAt: '2023-11-09T05:54:48.931Z',
        categoryId: 3,
      },
    },
  ],
  fields: [
    {
      name: 'id',
      type: 'bigInt',
      interface: 'id',

      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      uiSchema: {
        type: 'number',
        title: '{{t("ID")}}',
        'x-component': 'InputNumber',
        'x-read-pretty': true,
      },
    },
    {
      name: 'base_unit_id',
      type: 'bigInt',
      interface: 'integer',
      isForeignKey: true,
      uiSchema: {
        type: 'number',
        title: 'base_unit_id',
        'x-component': 'InputNumber',
        'x-read-pretty': true,
      },
    },
    {
      name: 'group_id',
      type: 'bigInt',
      interface: 'integer',

      isForeignKey: true,
      uiSchema: {
        type: 'number',
        title: 'group_id',
        'x-component': 'InputNumber',
        'x-read-pretty': true,
      },
    },
    {
      name: 'createdAt',
      type: 'date',
      interface: 'createdAt',
      field: 'createdAt',
      uiSchema: {
        type: 'datetime',
        title: '{{t("Created at")}}',
        'x-component': 'DatePicker',
        'x-component-props': {},
        'x-read-pretty': true,
      },
    },
    {
      name: 'createdBy',
      type: 'belongsTo',
      interface: 'createdBy',
      target: 'users',
      foreignKey: 'createdById',
      uiSchema: {
        type: 'object',
        title: '{{t("Created by")}}',
        'x-component': 'AssociationField',
        'x-component-props': {
          fieldNames: {
            value: 'id',
            label: 'nickname',
          },
        },
        'x-read-pretty': true,
      },
      targetKey: 'id',
    },
    {
      name: 'updatedAt',
      type: 'date',
      interface: 'updatedAt',
      field: 'updatedAt',
      uiSchema: {
        type: 'string',
        title: '{{t("Last updated at")}}',
        'x-component': 'DatePicker',
        'x-component-props': {},
        'x-read-pretty': true,
      },
    },
    {
      name: 'updatedBy',
      type: 'belongsTo',
      interface: 'updatedBy',
      target: 'users',
      foreignKey: 'updatedById',
      uiSchema: {
        type: 'object',
        title: '{{t("Last updated by")}}',
        'x-component': 'AssociationField',
        'x-component-props': {
          fieldNames: {
            value: 'id',
            label: 'nickname',
          },
        },
        'x-read-pretty': true,
      },
      targetKey: 'id',
    },
    {
      name: 'name',
      type: 'string',
      interface: 'input',
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: '物料名称',
      },
    },
    {
      name: 'model',
      type: 'string',
      interface: 'input',
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: '规格型号图号',
      },
    },
    {
      name: 'is_multi_unit',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: {
        type: 'boolean',
        'x-component': 'Checkbox',
        title: '启用多单位',
      },
    },
    {
      name: 'color',
      type: 'string',
      interface: 'input',
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: '颜色',
      },
    },
    {
      name: 'size',
      type: 'string',
      interface: 'input',
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: '尺寸',
      },
    },
    {
      name: 'material',
      type: 'string',
      interface: 'input',
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: '材质',
      },
    },
    {
      name: 'brand',
      type: 'string',
      interface: 'input',
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: '品牌',
      },
    },
    {
      name: 'code',
      type: 'sequence',
      interface: 'sequence',
      patterns: [
        {
          type: 'string',
          options: {
            value: 'WL',
          },
        },
        {
          type: 'integer',
          options: {
            digits: 5,
            start: 1,
            key: 9845,
            cycle: null,
          },
        },
      ],
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        'x-component-props': {},
        title: '物料编码',
      },
      unique: true,
    },
    {
      name: 'fj_info',
      type: 'belongsToMany',
      interface: 'attachment',
      uiSchema: {
        'x-component-props': {
          accept: 'image/*',
          multiple: true,
        },
        type: 'array',
        'x-component': 'Upload.Attachment',
        title: '图片附件',
      },
      target: 'attachments',
      through: 't_glz1heeqp3w',
      foreignKey: 'f_nb25gquzo7j',
      otherKey: 'f_bmrbv6rmzng',
      targetKey: 'id',
      sourceKey: 'id',
      storage: 'wl',
    },
    {
      name: 'base_unit',
      type: 'belongsTo',
      interface: 'obo',
      foreignKey: 'base_unit_id',
      onDelete: 'SET NULL',
      uiSchema: {
        'x-component': 'AssociationField',
        'x-component-props': {
          multiple: false,
          fieldNames: {
            label: 'id',
            value: 'id',
          },
        },
        title: '计量单位',
      },
      target: 'base_units',
      targetKey: 'id',
    },
    {
      name: 'unit_info',
      type: 'hasMany',
      interface: 'o2m',
      foreignKey: 'wl_id',
      onDelete: 'SET NULL',
      uiSchema: {
        'x-component': 'AssociationField',
        'x-component-props': {
          multiple: true,
          fieldNames: {
            label: 'id',
            value: 'id',
          },
        },
        title: '单位设置',
      },
      target: 'wl_units',
      targetKey: 'id',
      sourceKey: 'id',
    },
    {
      name: 'price_info',
      type: 'hasMany',
      interface: 'o2m',
      foreignKey: 'wl_id',
      onDelete: 'SET NULL',
      uiSchema: {
        'x-component': 'AssociationField',
        'x-component-props': {
          multiple: true,
          fieldNames: {
            label: 'id',
            value: 'id',
          },
        },
        title: '价格设置',
      },
      target: 'wl_price',
      targetKey: 'id',
      sourceKey: 'id',
    },
    {
      name: 'group',
      type: 'belongsTo',
      interface: 'm2o',
      foreignKey: 'group_id',
      onDelete: 'SET NULL',
      uiSchema: {
        'x-component': 'AssociationField',
        'x-component-props': {
          multiple: false,
          fieldNames: {
            label: 'id',
            value: 'id',
          },
        },
        title: '物料分类',
      },
      target: 'wl_category',
      targetKey: 'id',
    },
  ],
  logging: true,
  autoGenId: true,
  createdBy: true,
  updatedBy: true,
  createdAt: true,
  updatedAt: true,
  sortable: true,
  template: 'general',
  view: false,
  schema: 'public',
  titleField: 'name',
};
